
obj-$(CONFIG_AMLOGIC_BOARD_HAS_AC)          += amlogic_ac_power.o
obj-$(CONFIG_AW_AXP)                        += axp_power/
obj-$(CONFIG_AML_PMU)                       += aml_pmu/
obj-$(CONFIG_RICOH_PMU)                     += ricoh/
obj-$(CONFIG_AMLOGIC_PMU_OF)                += aml_pmu_of_common.o pmu_mutex.o

obj-$(CONFIG_AML_DVFS)                      += aml_dvfs/
obj-$(CONFIG_WOL_POWER)  += wol_power.o
