#
# (C) Copyright 2000-2013
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#
#########################################################################

# This file is included from ./Makefile and spl/Makefile.
# Clean the state to avoid the same flags added twice.
#
# (Tegra needs different flags for SPL.
#  That's the reason why this file must be included from spl/Makefile too.
#  If we did not have Tegra SoCs, build system would be much simpler...)
PLATFORM_RELFLAGS :=
PLATFORM_CPPFLAGS :=
PLATFORM_LDFLAGS :=
LDFLAGS :=
LDFLAGS_FINAL :=
OBJCOPYFLAGS :=
# clear VENDOR for tcsh
VENDOR :=
#########################################################################

ARCH := $(CONFIG_SYS_ARCH:"%"=%)
CPU := $(CONFIG_SYS_CPU:"%"=%)
BOARD := $(CONFIG_SYS_BOARD:"%"=%)
ifneq ($(CONFIG_SYS_VENDOR),)
VENDOR := $(CONFIG_SYS_VENDOR:"%"=%)
endif
ifneq ($(CONFIG_SYS_SOC),)
SOC := $(CONFIG_SYS_SOC:"%"=%)
endif

# Some architecture config.mk files need to know what CPUDIR is set to,
# so calculate CPUDIR before including ARCH/SOC/CPU config.mk files.
# Check if arch/$ARCH/cpu/$CPU exists, otherwise assume arch/$ARCH/cpu contains
# CPU-specific code.
CPUDIR=arch/$(ARCH)/cpu$(if $(CPU),/$(CPU),)

sinclude $(srctree)/arch/$(ARCH)/config.mk	# include architecture dependend rules
sinclude $(srctree)/$(CPUDIR)/config.mk		# include  CPU	specific rules

ifdef	SOC
sinclude $(srctree)/$(CPUDIR)/$(SOC)/config.mk	# include  SoC	specific rules
endif
ifneq ($(BOARD),)
ifeq ($(CONFIG_SUPPORT_CUSOTMER_BOARD), y) #SUPPORT_CUSOTMER_BOARD
BOARDDIR = customer/board/$(BOARD)
else #SUPPORT_CUSOTMER_BOARD
ifdef	VENDOR
BOARDDIR = board/$(VENDOR)/$(BOARD)
else
BOARDDIR = board/$(BOARD)
endif
endif #SUPPORT_CUSOTMER_BOARD
endif
ifdef	BOARD
sinclude $(srctree)/$(BOARDDIR)/config.mk	# include board specific rules
endif

ifdef FTRACE
PLATFORM_CPPFLAGS += -finstrument-functions -DFTRACE
endif

# Allow use of stdint.h if available
ifneq ($(USE_STDINT),)
PLATFORM_CPPFLAGS += -DCONFIG_USE_STDINT
endif

#########################################################################

### UFBL flags
UFBL_FLAGS += -I$(buildtree)/include2
UFBL_FLAGS += -I$(buildtree)/include
UFBL_FLAGS += -I$(buildsrc)/include
UFBL_FLAGS += -D__KERNEL__ -D__HAVE_ARCH_BCOPY

RELFLAGS := $(PLATFORM_RELFLAGS)

OBJCOPYFLAGS += --gap-fill=0xff

PLATFORM_CPPFLAGS += $(RELFLAGS)
PLATFORM_CPPFLAGS += -pipe

LDFLAGS += $(PLATFORM_LDFLAGS)
LDFLAGS_FINAL += -Bstatic

FIRMWARE_CPPFLAGS += -I$(buildsrc)/include
FIRMWARE_CPPFLAGS += -I$(buildsrc)/arch/$(ARCH)/include
FIRMWARE_CPPFLAGS += -I$(buildtree)/include2 -I$(buildtree)/include
FIRMWARE_CPPFLAGS += -include $(buildtree)/include/config.h
FIRMWARE_CPPFLAGS += -include $(buildtree)/include/generated/autoconf.h
FIRMWARE_CPPFLAGS += -include $(buildtree)/include/generated/version_autogenerated.h
FIRMWARE_CPPFLAGS += -fno-builtin -ffreestanding -nostdinc	\
	-isystem $(gccincdir) -pipe $(PLATFORM_CPPFLAGS)
FIRMWARE_CPPFLAGS += -I$(buildsrc)/board/$(BOARDDIR)/firmware

export FIRMWARE_CPPFLAGS
export PLATFORM_CPPFLAGS
export RELFLAGS
export LDFLAGS_FINAL
export CONFIG_STANDALONE_LOAD_ADDR

### UFBL config
# DEFINES was defined in ufbl
UFBL_FLAGS += $(DEFINES)
#
# # Allow boards to use custom optimize flags on a per dir/file basis
BCURDIR = $(subst $(SRCTREE)/,,$(CURDIR:$(obj)%=%))
ALL_AFLAGS = $(AFLAGS) $(AFLAGS_$(BCURDIR)/$(@F)) $(AFLAGS_$(BCURDIR))
ALL_CFLAGS = $(CFLAGS) $(CFLAGS_$(BCURDIR)/$(@F)) $(CFLAGS_$(BCURDIR)) $(UFBL_FLAGS)

### UFBL config
$(obj)%.s:	%.S
	@mkdir -p $(@D)
	$(CPP) $(ALL_AFLAGS) -o $@ $<
$(obj)%.o:	%.S
	@mkdir -p $(@D)
	$(CC)  $(ALL_AFLAGS) -o $@ $< -c
$(obj)%.o:	%.c
	@mkdir -p $(@D)
	$(CC)  $(ALL_CFLAGS) -o $@ $< -c
$(obj)%.i:	%.c
	@mkdir -p $(@D)
	$(CPP) $(ALL_CFLAGS) -o $@ $< -c
$(obj)%.s:	%.c
	@mkdir -p $(@D)
	$(CC)  $(ALL_CFLAGS) -o $@ $< -c -S

# add for old uboot version compatible
cmd_link_o_target = $(if $(strip $1),\
		    $(LD) $(LDFLAGS) -r -o $@ $1,\
		    rm -f $@; $(AR) rcs $@ )
